// export { DashboardShell } from './components/DashboardShell.js'
// export { DashboardProvider, useDashboard } from './DashboardContext.js'
// export { WidgetGrid } from './components/WidgetGrid.js'
// export { WidgetCard } from './components/WidgetCard.js'
// export { TableWidget } from './components/TableWidget.js'
// export { ChartWidget } from './components/ChartWidget.js'
// export { MetricWidget } from './components/MetricWidget.js'
// export { AddWidgetModal } from './components/AddWidgetModal.js'
// export type { Widget, WidgetType, DashboardConfig } from './types.js'

export { DashboardShell } from './components/DashboardShell.js'
export { DashboardProvider, useDashboard } from './DashboardContext.js'
export { WidgetGrid } from './components/WidgetGrid.js'
export { WidgetCard } from './components/WidgetCard.js'
export { TableWidget } from './components/TableWidget.js'
export { ChartWidget } from './components/ChartWidget.js'
export { MetricWidget } from './components/MetricWidget.js'
export { AddWidgetModal } from './components/AddWidgetModal.js'
export { CopilotProvider, useCopilot } from './copilot/CopilotContext.js'
export { CopilotPanel } from './copilot/CopilotPanel.js'
export { MessageBubble } from './copilot/MessageBubble.js'
export { MessageList } from './copilot/MessageList.js'
export { ChatInput } from './copilot/ChatInput.js'
export type { Widget, WidgetType, DashboardConfig } from './types.js'
export type { ChatMessage, MessageRole } from './copilot/types.js'
