import { existsSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { input, select, password, confirm } from '@inquirer/prompts'
import chalk from 'chalk'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

function getRepoRoot(): string {
  return resolve(__dirname, '../../..')
}

function envPaths() {
  const root = getRepoRoot()
  return {
    envFile: resolve(root, '.env'),
  }
}

export function needsSetup(): boolean {
  const { envFile } = envPaths()
  return !existsSync(envFile)
}

export async function runSetupWizard(): Promise<boolean> {
  const { envFile } = envPaths()

  console.log()
  console.log(chalk.cyan.bold('  Welcome to OpenDB '))
  console.log(chalk.dim("  Let's get you set up. This only takes a minute."))
  console.log()

  // Step 1: Database
  console.log(chalk.yellow.bold('  ── Database ──'))
  const dbType = await select({
    message: 'Which database are you using?',
    choices: [
      { name: 'PostgreSQL', value: 'postgresql' },
      { name: 'MongoDB', value: 'mongodb' },
    ],
  })

  let pgConn = ''
  let mongoUri = ''
  let mongoDbName = ''

  if (dbType === 'postgresql') {
    pgConn = await input({
      message: 'PostgreSQL connection string:',
      default: 'postgresql://postgres:password@localhost:5433/erp_demo',
      validate: (v) => v.startsWith('postgresql://') || 'Must start with postgresql://',
    })
  } else {
    mongoUri = await input({
      message: 'MongoDB URI:',
      default: 'mongodb://localhost:27017',
      validate: (v) =>
        v.startsWith('mongodb://') ||
        v.startsWith('mongodb+srv://') ||
        'Must start with mongodb://',
    })
    mongoDbName = await input({
      message: 'MongoDB database name:',
      default: 'erp_demo',
    })
  }

  // Step 2: AI Provider
  console.log()
  console.log(chalk.yellow.bold('  ── AI Provider ──'))
  const provider = await select({
    message: 'Which AI provider?',
    choices: [
      { name: 'Claude (Anthropic)', value: 'claude' },
      { name: 'OpenAI', value: 'openai' },
      { name: 'Gemini (Google)', value: 'gemini' },
      { name: 'Grok (xAI)', value: 'grok' },
    ],
  })

  const modelDefaults: Record<string, string> = {
    claude: 'claude-sonnet-4-20250514',
    openai: 'gpt-4o',
    gemini: 'gemini-1.5-pro',
    grok: 'grok-beta',
  }

  const model = await input({
    message: 'Model name:',
    default: modelDefaults[provider] ?? '',
  })

  const keyEnvNames: Record<string, string> = {
    claude: 'ANTHROPIC_API_KEY',
    openai: 'OPENAI_API_KEY',
    gemini: 'GEMINI_API_KEY',
    grok: 'GROK_API_KEY',
  }

  const keyLabels: Record<string, string> = {
    claude: 'Anthropic API key',
    openai: 'OpenAI API key',
    gemini: 'Gemini API key',
    grok: 'Grok API key',
  }

  const apiKey = await password({
    message: keyLabels[provider] ?? 'API key:',
    validate: (v) => v.length > 0 || 'API key is required',
    mask: '*',
  })

  // Step 3: Optional settings
  console.log()
  console.log(chalk.yellow.bold('  ── Options ──'))
  const port = await input({
    message: 'Server port:',
    default: '3005',
    validate: (v) => !isNaN(Number(v)) || 'Must be a number',
  })

  const useFallback = await confirm({
    message: 'Configure a fallback AI model?',
    default: false,
  })

  let fallbackModel = ''
  if (useFallback) {
    fallbackModel = await input({
      message: 'Fallback model name:',
      default: 'gpt-4o',
    })
  }

  // Generate .env content
  console.log()
  console.log(chalk.yellow.bold('  ── Writing Config ──'))

  const lines: string[] = [
    '# OpenDB Configuration',
    '# Generated by setup wizard',
    '',
    '# AI Provider',
    `AI_PROVIDER=${provider}`,
    `AI_MODEL=${model}`,
    `AI_PROMPT_VERSION=v1`,
    `AI_MAX_SCHEMA_COLLECTIONS=8`,
    '',
    '# API Keys',
    `${keyEnvNames[provider] ?? 'API_KEY'}=${apiKey}`,
  ]

  if (fallbackModel) {
    lines.push(`AI_FALLBACK_MODEL=${fallbackModel}`)
  }

  lines.push('')
  lines.push('# Database')
  lines.push(`DB_TYPE=${dbType}`)

  if (dbType === 'postgresql') {
    lines.push(`PG_CONNECTION_STRING=${pgConn}`)
  } else {
    lines.push(`MONGO_URI=${mongoUri}`)
    lines.push(`MONGO_DB_NAME=${mongoDbName}`)
  }

  lines.push('')
  lines.push('# Server')
  lines.push(`PORT=${port}`)
  lines.push('')

  await writeFile(envFile, lines.join('\n'), 'utf-8')

  console.log(chalk.green('  ✓ ') + `Created ${envFile}`)

  // Step 4: Quick connection test
  console.log()
  console.log(chalk.yellow.bold('  ── Testing Connection ──'))

  try {
    // Dynamic import to test
    const { createCopilotRuntime } = await import('./copilotRuntime.js')
    const rt = createCopilotRuntime()
    await rt.connector.connect()
    console.log(chalk.green('  ✓ ') + `Database connected (${dbType})`)
    console.log(chalk.green('  ✓ ') + `AI provider ready (${provider} · ${model})`)
  } catch (err) {
    console.log(chalk.yellow('  ⚠ ') + 'Connection test failed — you can fix this later')
    console.log(chalk.dim(`    ${err instanceof Error ? err.message : String(err)}`))
  }

  // Done
  console.log()
  console.log(chalk.cyan.bold('  Setup complete! '))
  console.log(chalk.dim('  Run `opendb` to start the interactive session.'))
  console.log(chalk.dim('  Run `opendb doctor` to verify your setup.'))
  console.log()

  return true
}
